export const legalConfig = {
  companyName: "Requo",
  productName: "Requo",
  supportEmail: "support@requo.app",
  privacyEmail: "privacy@requo.app",
  domain: "https://requo.app",
  address: "Lucena City, Quezon, Philippines",
  country: "Philippines",
  effectiveDate: "September 17, 2026",
  hostingProvider: "Vercel",
  storageProvider: "Supabase",
  paymentProvider: "Polar",
  governingLaw: "The laws of the Republic of the Philippines",
  venue: "the proper courts of Lucena City, Quezon, Philippines",
} as const;
