import Link from "next/link";

import { legalConfig } from "@/features/legal/config";
import {
  LegalDocumentPage,
  type LegalDocumentSection,
  LegalList,
  LegalParagraph,
  LegalSectionHeading,
  LegalSubheading,
} from "@/features/legal/components/legal-document-page";

const dpaSections: LegalDocumentSection[] = [
  {
    id: "introduction",
    title: "1. Introduction",
    content: (
      <>
        <LegalSectionHeading>1. Introduction</LegalSectionHeading>
        <LegalParagraph>
          This Data Processing Agreement (&quot;DPA&quot;) forms part of the
          agreement between you (&quot;Controller&quot;) and{" "}
          {legalConfig.companyName} (&quot;Processor&quot;) for the provision of
          the {legalConfig.productName} service. This DPA governs the processing
          of personal data by the Processor on behalf of the Controller.
        </LegalParagraph>
        <LegalParagraph>
          {legalConfig.companyName} acts as a Processor when processing business
          customer data on behalf of businesses that use {legalConfig.productName}
          . The business (Controller) determines the purposes and means of
          processing personal data submitted through the Service.
        </LegalParagraph>
      </>
    ),
  },
  {
    id: "definitions",
    title: "2. Definitions",
    content: (
      <>
        <LegalSectionHeading>2. Definitions</LegalSectionHeading>
        <LegalList
          items={[
            <span key="controller">
              <strong>&quot;Controller&quot;</strong> means the business entity
              that determines the purposes and means of processing personal data
              using the Service.
            </span>,
            <span key="processor">
              <strong>&quot;Processor&quot;</strong> means {legalConfig.companyName}
              , which processes personal data on behalf of the Controller.
            </span>,
            <span key="data-subject">
              <strong>&quot;Data Subject&quot;</strong> means an identified or
              identifiable natural person whose personal data is processed.
            </span>,
            <span key="personal-data">
              <strong>&quot;Personal Data&quot;</strong> means any information
              relating to a Data Subject that is processed through the Service.
            </span>,
            <span key="subprocessor">
              <strong>&quot;Subprocessor&quot;</strong> means a third party
              engaged by the Processor to process Personal Data on behalf of the
              Controller.
            </span>,
            <span key="scc">
              <strong>&quot;Standard Contractual Clauses&quot; (SCCs)</strong>{" "}
              means the contractual clauses adopted by the European Commission
              for transfers of personal data to third countries.
            </span>,
          ]}
        />
      </>
    ),
  },
  {
    id: "scope-and-role",
    title: "3. Scope and Role of the Processor",
    content: (
      <>
        <LegalSectionHeading>
          3. Scope and Role of the Processor
        </LegalSectionHeading>
        <LegalParagraph>
          {legalConfig.companyName} is designated as the Processor for all
          business customer data processed through the Service. The Controller
          instructs the Processor to process Personal Data only as necessary to
          provide the Service, as described in the Terms of Service and this DPA.
        </LegalParagraph>
        <LegalSubheading>Categories of Data Subjects</LegalSubheading>
        <LegalList
          items={[
            "End users who submit inquiries through the Controller's public inquiry forms",
            "Recipients of quotes generated by the Controller through the Service",
            "Business contacts managed by the Controller within the Service",
          ]}
        />
        <LegalSubheading>Categories of Personal Data</LegalSubheading>
        <LegalList
          items={[
            "Contact information (name, email address, phone number)",
            "Inquiry content and communications",
            "Quote details and response data",
            "Files and attachments uploaded through the Service",
          ]}
        />
        <LegalSubheading>Processing Activities</LegalSubheading>
        <LegalList
          items={[
            "Storage and retrieval of inquiry and quote data",
            "Email delivery for quote sharing and notifications",
            "AI-assisted drafting of quotes and responses",
            "Analytics and reporting on inquiry and quote activity",
          ]}
        />
      </>
    ),
  },
  {
    id: "standard-contractual-clauses",
    title: "4. Standard Contractual Clauses (Module 2)",
    content: (
      <>
        <LegalSectionHeading>
          4. Standard Contractual Clauses (Module 2: Controller-to-Processor)
        </LegalSectionHeading>
        <LegalParagraph>
          For transfers of Personal Data from the European Economic Area (EEA),
          United Kingdom, or Switzerland to countries that have not received an
          adequacy decision, the parties agree to be bound by the Standard
          Contractual Clauses (Module 2: Controller-to-Processor) as adopted by
          the European Commission Decision 2021/914.
        </LegalParagraph>
        <LegalSubheading>Module 2 Applicability</LegalSubheading>
        <LegalParagraph>
          Module 2 applies where the Controller (data exporter) transfers
          Personal Data to the Processor (data importer) located in a third
          country. Under Module 2:
        </LegalParagraph>
        <LegalList
          items={[
            "The Controller determines the purposes and means of processing",
            "The Processor processes Personal Data only on documented instructions from the Controller",
            "The Processor ensures that persons authorized to process Personal Data have committed to confidentiality",
            "The Processor implements appropriate technical and organizational measures to ensure data security",
            "The Processor assists the Controller with data subject requests and compliance obligations",
            "The Processor deletes or returns all Personal Data upon termination of the Service, at the Controller's choice",
          ]}
        />
        <LegalSubheading>Supplementary Measures</LegalSubheading>
        <LegalParagraph>
          In addition to the SCCs, the Processor implements supplementary
          technical and organizational measures as described in the Technical and
          Organizational Measures Annex below, to ensure an adequate level of
          protection for transferred Personal Data.
        </LegalParagraph>
      </>
    ),
  },
  {
    id: "technical-organizational-measures",
    title: "5. Technical and Organizational Measures Annex",
    content: (
      <>
        <LegalSectionHeading>
          5. Technical and Organizational Measures Annex
        </LegalSectionHeading>
        <LegalParagraph>
          The Processor implements and maintains the following technical and
          organizational measures to protect Personal Data:
        </LegalParagraph>

        <LegalSubheading>Encryption</LegalSubheading>
        <LegalList
          items={[
            "TLS 1.3 encryption for all data in transit",
            "AES-256 encryption for all data at rest (via Supabase managed storage)",
            "Encrypted database connections between application and database layers",
            "Secure key management through infrastructure provider controls",
          ]}
        />

        <LegalSubheading>Access Control</LegalSubheading>
        <LegalList
          items={[
            "Role-based access control (RBAC) with business-scoped data isolation",
            "Authentication via email verification, OAuth providers, and magic links",
            "Session management with secure, HttpOnly cookies",
            "Principle of least privilege for all system access",
            "Business-scoped data isolation ensuring users access only their own business data",
          ]}
        />

        <LegalSubheading>Monitoring and Logging</LegalSubheading>
        <LegalList
          items={[
            "Security event logging for authentication and access events",
            "Rate limiting on public-facing endpoints to prevent abuse",
            "AI security event monitoring for prompt injection attempts",
            "Audit logging for sensitive business actions",
          ]}
        />

        <LegalSubheading>Incident Response</LegalSubheading>
        <LegalList
          items={[
            "Notification to affected Controllers within 72 hours of confirming a Personal Data breach",
            "Documentation of security incidents including nature, scope, and remediation steps",
            "Cooperation with Controllers in fulfilling their breach notification obligations",
            "Post-incident review and implementation of preventive measures",
          ]}
        />

        <LegalSubheading>Data Minimization and Retention</LegalSubheading>
        <LegalList
          items={[
            "Processing limited to what is necessary for providing the Service",
            "Defined retention periods per data category (see Privacy Policy)",
            "Secure deletion of data upon account termination after the export window",
            "AI provider data processed with zero-data-retention policies where available",
          ]}
        />
      </>
    ),
  },
  {
    id: "subprocessors",
    title: "6. Subprocessors",
    content: (
      <>
        <LegalSectionHeading>6. Subprocessors</LegalSectionHeading>
        <LegalParagraph>
          The Controller provides general authorization for the Processor to
          engage Subprocessors to assist in providing the Service. The Processor
          maintains a current list of Subprocessors, including their purpose and
          data locations.
        </LegalParagraph>
        <LegalParagraph>
          The current list of Subprocessors is available at{" "}
          <Link
            className="text-foreground underline-offset-4 hover:underline"
            href="/subprocessors"
          >
            requo.app/subprocessors
          </Link>
          .
        </LegalParagraph>
        <LegalParagraph>
          The Processor shall notify the Controller of any intended changes to
          Subprocessors, giving the Controller the opportunity to object. The
          Processor ensures that each Subprocessor is bound by data protection
          obligations no less protective than those in this DPA.
        </LegalParagraph>
      </>
    ),
  },
  {
    id: "controller-obligations",
    title: "7. Controller Obligations",
    content: (
      <>
        <LegalSectionHeading>7. Controller Obligations</LegalSectionHeading>
        <LegalParagraph>The Controller shall:</LegalParagraph>
        <LegalList
          items={[
            "Ensure a lawful basis exists for the processing of Personal Data",
            "Provide Data Subjects with appropriate privacy notices",
            "Ensure instructions to the Processor comply with applicable data protection laws",
            "Respond to Data Subject requests, with the Processor's reasonable assistance",
          ]}
        />
      </>
    ),
  },
  {
    id: "data-subject-rights",
    title: "8. Data Subject Rights",
    content: (
      <>
        <LegalSectionHeading>8. Data Subject Rights</LegalSectionHeading>
        <LegalParagraph>
          The Processor shall assist the Controller in responding to Data Subject
          requests to exercise their rights under applicable data protection law,
          including rights of access, rectification, erasure, restriction,
          portability, and objection.
        </LegalParagraph>
        <LegalParagraph>
          Where a Data Subject contacts the Processor directly, the Processor
          shall promptly redirect the request to the relevant Controller unless
          prohibited by law.
        </LegalParagraph>
      </>
    ),
  },
  {
    id: "term-and-termination",
    title: "9. Term and Termination",
    content: (
      <>
        <LegalSectionHeading>9. Term and Termination</LegalSectionHeading>
        <LegalParagraph>
          This DPA remains in effect for as long as the Processor processes
          Personal Data on behalf of the Controller. Upon termination of the
          Service agreement, the Processor shall, at the Controller&apos;s
          choice, delete or return all Personal Data within 30 days, except where
          retention is required by applicable law.
        </LegalParagraph>
        <LegalParagraph>
          The Controller may export their data using the data export feature
          during the 30-day post-termination window.
        </LegalParagraph>
      </>
    ),
  },
  {
    id: "governing-law",
    title: "10. Governing Law",
    content: (
      <>
        <LegalSectionHeading>10. Governing Law</LegalSectionHeading>
        <LegalParagraph>
          This DPA is governed by {legalConfig.governingLaw}. For transfers
          subject to the Standard Contractual Clauses, the SCCs shall be
          governed by the law of the EU Member State in which the Controller is
          established, or where the Controller is not established in the EU, the
          law of the country where the Processor is established.
        </LegalParagraph>
      </>
    ),
  },
  {
    id: "contact",
    title: "11. Contact",
    content: (
      <>
        <LegalSectionHeading>11. Contact</LegalSectionHeading>
        <LegalParagraph>
          For questions about this DPA or to request a signed copy, contact us
          at{" "}
          <a
            className="text-foreground underline-offset-4 hover:underline"
            href={`mailto:${legalConfig.privacyEmail}`}
          >
            {legalConfig.privacyEmail}
          </a>{" "}
          or by mail at {legalConfig.address}.
        </LegalParagraph>
      </>
    ),
  },
];

export function DpaPage() {
  return (
    <LegalDocumentPage
      sections={dpaSections}
      title="Data Processing Agreement"
    />
  );
}
